name: Publish PyPi
on:
  release:
    types: [published]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.7.2
      uses: actions/setup-python@v1
      with:
        python-version: '3.7.2'
    - name: Install Python 3.7.2 dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip3 install setuptools wheel twine
    - name: Build package
      run: |
        python3 setup.py sdist bdist_wheel --universal
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}